### ISSUE TITLE
Fails to install with weird error

### ISSUE THREAD

**Issue by nick8325** [jbransen/minisat-bundle#1]
On my machine, building minisat fails with the error `gcc: error: __STDC_LIMIT_MACROS: No such file or directory`. GHC is being invoked as follows:

```
/usr/bin/ghc -c -fPIC -odir dist/build -Idist/build/autogen -Idist/build -Iminisat-haskell-bindings -Iminisat-c-bindings -Iminisat -optc-O2 -optc__STDC_LIMIT_MACROS -optc-D -optc__STDC_FORMAT_MACROS -package-db dist/package.conf.inplace -package-id async-2.0.1.6-f3b8c6a4be17de4cc051024c7e1f2f16 -package-id base-4.7.0.1-e4b74d27ad8c8987c63abc42a80e7335 minisat-c-bindings/minisat.cc
```

Notice that `-optc` is being used to pass the options `__STDC_LIMIT_MACROS -D __STDC_FORMAT_MACROS` to the C compiler. This is weird because there should be a `-D` before `__STDC_LIMIT_MACROS`. In fact, the cabal file reads

```
CC-options:      -D __STDC_LIMIT_MACROS -D __STDC_FORMAT_MACROS
```

but the first `-D` is being eaten somehow!

Anyway, changing the cabal file so that it reads

```
CC-options:      -D__STDC_LIMIT_MACROS -D__STDC_FORMAT_MACROS
```

(i.e., removing the spaces between the `-D` and the macro) fixes the problem, though I don't know what's happening.

This happens both on a Linux machine and a Mac, both running GHC 7.8.3, so I don't think it's a broken installation.

**Comment by jwaldmann** [comment]
same here. I am quite sure it worked at some point, so I think it is due to some change in cabal.

anyway the above patch should be applied, and the result should be pushed to hackage.

**Comment by jbransen** [comment]
Fixed, thanks for reporting!
