### ISSUE TITLE
minisat_setDecisionVar and minisat_setPolarity shoud accept Bool instead Int

### ISSUE THREAD

**Issue by jachymb** [jbransen/minisat-bundle#3]
The signatures in minisat source are: 

      void    setPolarity    (Var v, lbool b); // Declare which polarity the decision heuristic should use for a variable. Requires mode 'polarity_user'.
      void    setDecisionVar (Var v, bool b);  // Declare if a variable should be eligible for selection in the decision heuristic.

But in the bundle it is

    minisat_setPolarity :: Solver -> Var -> Int -> IO () 
    minisat_setDecisionVar :: Solver -> Var -> Int -> IO ()

**Comment by jbransen** [comment]
Where do you see these signatures? The [sources that are used](https://github.com/niklasso/minisat-c-bindings/blob/2f137cbedc7a1a0ecd4117baaf84a005c2045134/minisat.h#L76) specify both as int.

Also, note that this repository is only bundling some other repos into a Haskell package, the Haskell binding package lives [here](https://github.com/niklasso/minisat-haskell-bindings/)

**Comment by jachymb** [comment]
I was referring to this: https://github.com/niklasso/minisat/blob/master/minisat/core/Solver.h#L91
